modified ansible hosts

diff --git a/monolithic-cicd/Jenkinsfile b/monolithic-cicd/Jenkinsfile
--- a/monolithic-cicd/Jenkinsfile
+++ b/monolithic-cicd/Jenkinsfile
@@ -94,13 +94,13 @@ pipeline {
                         set -ex
                         mkdir -p ~/itgenius-app/
                         cd ~/itgenius-app/
-
-                        # Stop the existing application if running
-                        pkill -f "itgenuine-0.0.1-SNAPSHOT.jar" || true
-
-                        # Run the new application
-                        java -jar itgenuine-0.0.1-SNAPSHOT.jar > logfile 2>&1 &
-                        echo "Started new itgenius application"
+                        nohup java -jar itgenuine-0.0.1-SNAPSHOT.jar > logfile 2>&1 &
+                        sleep 10
+                        if ! pgrep -f "itgenuine-0.0.1-SNAPSHOT.jar" > /dev/null; then
+                            echo "Application failed to start."
+                            exit 1
+                        fi
+                        echo "Application started successfully."
                         sleep 7
                         cat logfile
                     '''
@@ -133,18 +133,6 @@ pipeline {
             }
         }
 
-        stage('Verify Prerequisites') {
-            steps {
-                sshCommand remote: remoteServerConfig, command: '''
-                    if ! command -v lsof &> /dev/null
-                    then
-                        echo "lsof is not installed. Installing..."
-                        sudo yum install -y lsof || sudo apt-get install -y lsof
-                    else
-                        echo "lsof is already installed."
-                    fi
-                '''
-            }
-        }
+        
     }
 }
